baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CV'

defaultContentLanguage = "en" # "en" or "fa"
enableRobotsTXT = true
enableEmoji = true

disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#dbdbdb"
colorIconPrimary = "#ccc"
colorIconSecondary = "#e3bfb8"
colorIconBackground = "#dbdbdb"
colorLeftColumnBackground = "#333"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
pages = 1
